---
- name: Master
  hosts: localhost
  become: false
  tasks:
    - name: USERAPPS | Find User Home Directory
      set_fact:
        pv_ua_user_home_dir: "{{  ansible_facts.user_dir  }}"
      tags: always

    - name: USERAPPS | Find User Config Directory
      tags: always
      set_fact:
        pv_ua_user_config_dir: "{{  pv_ua_user_home_dir  }}/.config"

    - name: USERAPPS | Find User local Directory
      tags: always
      set_fact:
        pv_ua_user_local_dir: "{{  pv_ua_user_home_dir  }}/.local"

    - name: USERAPPS | Find User Share Directory
      tags: always
      set_fact:
        pv_ua_user_share_dir: "{{  pv_ua_user_local_dir  }}/share"

    - name: USERAPPS | Find User temp Directory
      tags: always
      set_fact:
        pv_ua_user_tmp_dir: "{{  pv_ua_user_home_dir  }}/.tmp/userapps"

    - name: USERAPPS | Install Terminal Themes
      import_tasks: tasks/terminal_themes.yml
      tags: terminal_themes

    - name: USERAPPS | Install Terminal Themes
      import_tasks: tasks/bitwarden_desktop.yml
      tags: bw
