---
- name: addhost
  hosts: localhost
  become: false
  gather_facts: true
  tasks:
    - name: addhost
      add_host:
        hostname: 'user_host'
        ansible_host: '192.168.175.128'
        ansible_ssh_user: user1
      tags: always
      changed_when: false

- name: Master
  hosts: user_host
  become: false
  gather_facts: true
  tasks:
    - name: USERAPPS | Find User Home Directory
      set_fact:
        pv_ua_user_home_dir: "{{  ansible_facts.user_dir  }}"
      tags: always

    - name: USERAPPS | Find User Config Directory
      tags: always
      set_fact:
        pv_ua_user_config_dir: "{{  pv_ua_user_home_dir  }}/.config"

    - name: USERAPPS | Find User local Directory
      tags: always
      set_fact:
        pv_ua_user_local_dir: "{{  pv_ua_user_home_dir  }}/.local"

    - name: USERAPPS | Find User bin Directory
      tags: always
      set_fact:
        pv_ua_user_bin_dir: "{{  pv_ua_user_local_dir  }}/bin"

    - name: USERAPPS | Find User Share Directory
      tags: always
      set_fact:
        pv_ua_user_share_dir: "{{  pv_ua_user_local_dir  }}/share"

    - name: USERAPPS | Find User temp Directory
      tags: always
      set_fact:
        pv_ua_user_tmp_dir: "{{  pv_ua_user_home_dir  }}/.tmp/userapps"

    - name: USERAPPS | Create a directory if it does not exist
      tags: always
      ansible.builtin.file:
        path: "{{  item  }}"
        state: directory
      with_items:
        - "{{  pv_ua_user_share_dir  }}/applications"
        - "{{  pv_ua_user_bin_dir  }}"
        - "{{  pv_ua_user_share_dir  }}/themes"
        - "{{  pv_ua_user_share_dir  }}/plasma/desktoptheme"
        - "{{  pv_ua_user_share_dir  }}/aurorae/themes"
        - "{{  pv_ua_user_share_dir  }}/color-schemes"
        - "{{  pv_ua_user_share_dir  }}/plasma/look-and-feel"
        - "{{  pv_ua_user_config_dir  }}/Kvantum"
        - "{{  pv_ua_user_config_dir  }}/konsave"
        - "{{  pv_ua_user_tmp_dir  }}"
        - "{{  pv_ua_user_share_dir  }}/konsole"
        - "{{  pv_ua_user_share_dir  }}/icons/Nordic-cursors"
        - "{{  pv_ua_user_share_dir  }}/fonts"

    - name: USERAPPS | Install Terminal Themes
      import_tasks: tasks/terminal_themes.yml
      tags: terminal_themes

    - name: USERAPPS | Install Bitwarden
      import_tasks: tasks/bitwarden_desktop.yml
      tags: bw

    - name: USERAPPS | Install Bitwarden CLI
      import_tasks: tasks/bitwarden_cli.yml
      tags: bw_cli

    - name: USERAPPS | Mattermost
      import_tasks: tasks/mattermost_desktop.yml
      tags: mattermost

    - name: USERAPPS | Telegram
      import_tasks: tasks/telegram_desktop.yml
      tags: telegram

    - name: USERAPPS | NodeJS
      import_tasks: tasks/nodejs.yml
      tags: nodejs

    - name: USERAPPS | nvim
      import_tasks: tasks/nvim.yml
      tags: nvim

    - name: USERAPPS | Postman
      import_tasks: tasks/postman.yml
      tags: postman

    - name: USERAPPS | Jq
      import_tasks: tasks/jq.yml
      tags: jq

    - name: USERAPPS | GoLang
      import_tasks: tasks/go.yml
      tags: go

    - name: USERAPPS | jdk
      import_tasks: tasks/jdk.yml
      tags: jdk

    - name: USERAPPS | Apache Maven
      import_tasks: tasks/mvn.yml
      tags: mvn

    - name: USERAPPS | VSCode
      import_tasks: tasks/code.yml
      tags: code

    - name: USERAPPS | kde
      import_tasks: tasks/download_kde_themes.yml
      tags:
        - never
        - kde

    - name: Dotfiles
      import_tasks: tasks/dotfiles.yml
      tags:
        - never
        - dotfiles

    - name: fonts
      import_tasks: tasks/fonts.yml
      tags:
        - never
        - fonts
