- name: USERAPPS | Dotfiles | Cloning git bare
  ansible.builtin.git:
    single_branch: true
    repo: 'https://github.com/arpanrec/dotfiles.git'
    dest: "{{  pv_ua_user_home_dir  }}/.dotfiles"
    depth: 1
    bare: true
