- name: USERAPPS | Icon | vinceliuice Tela
  block:
    - name: USERAPPS | Icon | vinceliuice Tela | Git Clone
      ansible.builtin.git:
        single_branch: true
        repo: "https://github.com/vinceliuice/Tela-icon-theme.git"
        dest: "{{  pv_ua_user_tmp_dir  }}/vinceliuice-Tela-icon-theme"
        depth: 1
      register: pv_kde_tmp_tela_icon_updated

    - name: USERAPPS | Icon | vinceliuice Tela | Install
      when: pv_kde_tmp_tela_icon_updated.changed
      block:
        - name: USERAPPS | Icon | vinceliuice Tela | Install | Execute install script
          ansible.builtin.shell: "{{  pv_ua_user_tmp_dir  }}/vinceliuice-Tela-icon-theme/install.sh -a"
          args:
            executable: /bin/bash
            # creates: "{{  pv_ua_user_share_dir  }}/icons/Tela"
          register: pv_kde_tmp_tela_icon_update_shell_result

        - name: USERAPPS | Icon | vinceliuice Tela | Install | Result
          ansible.builtin.debug:
            var: pv_kde_tmp_tela_icon_update_shell_result

- name: USERAPPS | Icon | EliverLara Candy
  block:
    - name: USERAPPS | Icon | EliverLara Candy | Git clone
      ansible.builtin.git:
        single_branch: true
        repo: "https://github.com/EliverLara/candy-icons.git"
        dest: "{{  pv_ua_user_tmp_dir  }}/EliverLara-candy-icons-git/"
        depth: 1
      register: pv_kde_tmp_eliverLara_candy_icon_updated

    - name: USERAPPS | Icon | EliverLara Candy | Copy Resources
      when: pv_kde_tmp_eliverLara_candy_icon_updated.changed
      block:
        - name: USERAPPS | Icon | EliverLara Candy | Copy Resources | Copy icons
          ansible.builtin.copy:
            src: "{{  pv_ua_user_tmp_dir  }}/EliverLara-candy-icons-git/"
            dest: "{{  pv_ua_user_share_dir  }}/icons/candy-icons/"
            remote_src: true

        - name: USERAPPS | Icon | EliverLara Candy | Copy Resources | Delete git tracker from gtk directory
          ansible.builtin.file:
            path: "{{  pv_ua_user_share_dir  }}/icons/candy-icons//.git"
            state: absent

- name: USERAPPS | Cursors | vinceliuice Layan-cursors
  block:
    - name: USERAPPS | Cursors | vinceliuice Layan-cursors | Git Clone
      ansible.builtin.git:
        single_branch: true
        repo: "https://github.com/vinceliuice/Layan-cursors.git"
        dest: "{{  pv_ua_user_tmp_dir  }}/vinceliuice-Layan-cursors"
        depth: 1
      register: pv_kde_tmp_layan_cursors_updated

    - name: USERAPPS | Cursors | vinceliuice Layan-cursors | Install
      when: pv_kde_tmp_layan_cursors_updated.changed
      block:
        - name: USERAPPS | Cursors | vinceliuice Layan-cursors | Install | Execute install script
          ansible.builtin.shell: "{{  pv_ua_user_tmp_dir  }}/vinceliuice-Layan-cursors/install.sh"
          args:
            executable: /bin/bash
            chdir: "{{  pv_ua_user_tmp_dir  }}/vinceliuice-Layan-cursors"
          register: pv_kde_tmp_layan_cursors_shell_install_result

        - name: USERAPPS | Cursors | vinceliuice Layan-cursors | Install | Result
          ansible.builtin.debug:
            var: pv_kde_tmp_layan_cursors_shell_install_result

- name: USERAPPS | Icon | Gvolpe BeautyLine
  block:
    - name: USERAPPS | Icon | Gvolpe BeautyLine | Git Clone
      ansible.builtin.git:
        single_branch: true
        repo: "https://github.com/gvolpe/BeautyLine.git"
        dest: "{{  pv_ua_user_tmp_dir  }}/gvolpe-BeautyLine"
        depth: 1
      register: pv_kde_tmp_gvolpe_beautyline_updated

    - name: USERAPPS | Icon | Gvolpe BeautyLine | Copy Resources | Copy icons
      when: pv_kde_tmp_gvolpe_beautyline_updated.changed
      ansible.builtin.copy:
        src: "{{  pv_ua_user_tmp_dir  }}/gvolpe-BeautyLine/BeautyLine-V3/"
        dest: "{{  pv_ua_user_share_dir  }}/icons/BeautyLine-V3/"
        remote_src: true
