- name: USERAPPS | Oracle JDK | Set install directory
  set_fact:
    pv_ua_jdk_install_path: "{{  pv_ua_user_share_dir  }}/java"

- name: USERAPPS | Oracle JDK | Set Version Tag
  set_fact:
    pv_ua_jdk_version: 17

- name: USERAPPS | Oracle JDK | Set Download URL
  set_fact:
    pv_ua_jdk_download_url: "https://download.oracle.com/java/{{  pv_ua_jdk_version  }}/latest/jdk-{{  pv_ua_jdk_version  }}_linux-x64_bin.tar.gz"
  when: ansible_facts.architecture == "x86_64"

- name: USERAPPS | Oracle JDK | Create install directory
  ansible.builtin.file:
    path: "{{  pv_ua_jdk_install_path  }}"
    state: directory

- name: USERAPPS | Oracle JDK | Set tarball download path.
  set_fact:
    pv_ua_jdk_tarball_download_path: "{{  pv_ua_user_tmp_dir  }}/jdk-{{  pv_ua_jdk_version  }}_linux-x64_bin.tar.gz"

- name: USERAPPS | Oracle JDK | Get downloaded file stat
  stat:
    path: "{{  pv_ua_jdk_tarball_download_path  }}"
  register: pv_ua_jdk_downloaded_file_stat

- name: USERAPPS | Oracle JDK | Newly Downloaded
  when: not pv_ua_jdk_downloaded_file_stat.stat.exists

  - name: USERAPPS | Oracle JDK | Download tarball
    ansible.builtin.get_url:
      url: "{{  pv_ua_jdk_download_url  }}"
      dest: "{{  pv_ua_jdk_tarball_download_path  }}"

  - name: USERAPPS | Oracle JDK | Unarchive the tarball
    ansible.builtin.unarchive:
      src: "{{  pv_ua_jdk_tarball_download_path  }}"
      dest: "{{  pv_ua_jdk_install_path  }}"
      extra_opts: [--strip-components=1]
      remote_src: true
