- name: USERAPPS | KDE | Find Konsave Profiles
  ansible.builtin.find:
    paths: "{{  playbook_dir  }}/files/"
    recurse: yes
    patterns: "*.knsv"
  delegate_to: localhost
  register: pv_kde_konsave_profiles

- name: USERAPPS | KDE | Find Konsave Profiles
  copy:
    src: "{{  item.path  }}"
    dest: "{{  pv_ua_user_tmp_dir  }}"
    remote_src: false
  with_items: "{{  pv_kde_konsave_profiles.files  }}"
  register: pv_kde_konsave_profiles_updated

- name: USERAPPS | KDE | Install konsave
  pip:
    name: konsave
  environment:
    PATH: "{{  pv_ua_user_bin_dir  }}:{{ ansible_env.PATH }}"

- name: USERAPPS | KDE | Import Konsave Profiles
  shell: "konsave --import-profile {{  pv_ua_user_tmp_dir  }}/{{  item.path  | basename }} --force"
  environment:
    PATH: "{{  pv_ua_user_bin_dir  }}:{{ ansible_env.PATH }}"
  with_items: "{{  pv_kde_konsave_profiles.files  }}"
  register: pv_kde_konsave_profiles_import_result
  when: pv_kde_konsave_profiles_updated.changed

- name: USERAPPS | KDE | Import Konsave Profiles Result
  debug:
    var: pv_kde_konsave_profiles_import_result
  when: pv_kde_konsave_profiles_updated.changed
