- name: USERAPPS | Mattermost Desktop | Set install directory
  set_fact:
    pv_ua_mm_install_path: "{{  pv_ua_user_share_dir  }}/mattermost-desktop"

- name: USERAPPS | Mattermost Desktop | Create install directory
  ansible.builtin.file:
    path: "{{  pv_ua_mm_install_path  }}"
    state: directory

- name: USERAPPS | Mattermost Desktop | Get latest releases
  ansible.builtin.uri:
    url: "https://api.github.com/repos/mattermost/desktop/releases/latest"
    method: GET
    return_content: yes
    headers:
      Accept: "application/vnd.github.v3+json"
    status_code: 200
  register: pv_ua_tmp_mm_latest_release

- name: USERAPPS | Mattermost Desktop | Get Release Version
  set_fact:
    pv_ua_mm_release_from_github: "{{  pv_ua_tmp_mm_latest_release.json.tag_name[1:]  }}"

- name: USERAPPS | Mattermost Desktop | Get os and architecture based download URL for x86_64
  set_fact:
    pv_ua_mm_download_url_appimage: "https://releases.mattermost.com/desktop/{{  pv_ua_mm_release_from_github  }}/mattermost-desktop-{{  pv_ua_mm_release_from_github  }}-linux-x64.tar.gz"
  when: ansible_facts.architecture == "x86_64"

- name: USERAPPS | Mattermost Desktop | Set archive download location
  set_fact:
    pv_ua_bw_mm_archive_download_path: "{{  pv_ua_user_tmp_dir  }}/mattermost-desktop-{{  pv_ua_mm_release_from_github  }}-linux.tar.gz"

- name: USERAPPS | Mattermost Desktop | Get archive info
  stat:
    path: "{{  pv_ua_bw_mm_archive_download_path  }}"
  register: pv_ua_mm_archive_stat

- name: USERAPPS | Mattermost Desktop | Newly Downloaded
  when: not pv_ua_mm_archive_stat.stat.exists
  block:
    - name: USERAPPS | Mattermost Desktop | Download in tmp path
      ansible.builtin.get_url:
        url: "{{  pv_ua_mm_download_url_appimage  }}"
        dest: "{{  pv_ua_bw_mm_archive_download_path  }}"

    - name: USERAPPS | Mattermost Desktop | Unarchive the tar ball
      ansible.builtin.unarchive:
        src: "{{  pv_ua_bw_mm_archive_download_path  }}"
        dest: "{{  pv_ua_mm_install_path  }}"
        extra_opts: [--strip-components=1]
        mode: "0750"
        remote_src: true

    - name: USERAPPS | Mattermost Desktop | Create desktop icon
      ansible.builtin.template:
        src: templates/mattermost-desktop-userapps.desktop.j2
        dest: "{{  pv_ua_user_share_dir  }}/applications/mattermost-desktop-userapps.desktop"
        mode: "0600"
