- name: USERAPPS | Postman | Set install directory
  set_fact:
    pv_ua_postman_install_path: "{{  pv_ua_user_share_dir  }}/Postman"

- name: USERAPPS | Postman | Create install directory
  ansible.builtin.file:
    path: "{{  pv_ua_postman_install_path  }}"
    state: directory

- name: USERAPPS | Postman | Set tarball download path.
  set_fact:
    pv_ua_postman_tarball_download_path: "{{  pv_ua_user_tmp_dir  }}/postman.tar.gz"

- name: USERAPPS | Postman | Set Download URL
  set_fact:
    pv_ua_postman_download_url: "https://dl.pstmn.io/download/latest/linux64"
  when: ansible_facts.architecture == "x86_64"

- name: USERAPPS | Postman | Get downloaded file stat
  stat:
    path: "{{  pv_ua_postman_tarball_download_path  }}"
  register: pv_ua_postman_tmp_downloaded_file_stat

- name: USERAPPS | Postman | Download tarball
  ansible.builtin.get_url:
    url: "{{  pv_ua_postman_download_url  }}"
    dest: "{{  pv_ua_postman_tarball_download_path  }}"
  when: not pv_ua_postman_tmp_downloaded_file_stat.stat.exists

- name: USERAPPS | Postman | Unarchive the tarball
  ansible.builtin.unarchive:
    src: "{{  pv_ua_postman_tarball_download_path  }}"
    dest: "{{  pv_ua_postman_install_path  }}"
    extra_opts: [--strip-components=1]
    remote_src: true

- name: USERAPPS | Postman | Create desktop icon
  ansible.builtin.template:
    src: templates/postman-userapps.desktop.j2
    dest: "{{  pv_ua_user_share_dir  }}/applications/postman-userapps.desktop"
    mode: '0600'
