---
- name: USERAPPS | Theme | EliverLara Nordic
  block:
    - name: USERAPPS | Theme | EliverLara Nordic | Clone git
      ansible.builtin.git:
        single_branch: true
        repo: "https://github.com/EliverLara/Nordic.git"
        dest: "{{  pv_ua_user_tmp_dir  }}/EliverLara-Nordic-git"
        depth: 1
      register: pv_kde_tmp_eliverLara_nordic_updated

    - name: USERAPPS | Theme | EliverLara Nordic | Copy Resources
      when: pv_kde_tmp_eliverLara_nordic_updated.changed
      block:
        - name: USERAPPS | Theme | EliverLara Nordic | Copy Resources | gtk themes
          ansible.builtin.copy:
            src: "{{  pv_ua_user_tmp_dir  }}/EliverLara-Nordic-git/"
            dest: "{{  pv_ua_user_share_dir  }}/themes/Nordic/"
            remote_src: true

        - name: USERAPPS | Theme | EliverLara Nordic | Copy Resources | Delete git tracker from gtk directory
          ansible.builtin.file:
            path: "{{  pv_ua_user_share_dir  }}/themes/Nordic/.git"
            state: absent

        - name: USERAPPS | Theme | EliverLara Nordic | Copy Resources | aurorae themes
          ansible.builtin.copy:
            src: "{{  pv_ua_user_share_dir  }}/themes/Nordic/kde/aurorae/Nordic/"
            dest: "{{  pv_ua_user_share_dir  }}/aurorae/themes/Nordic/"
            remote_src: true

        - name: USERAPPS | Theme | EliverLara Nordic | Copy Resources | color schemes
          ansible.builtin.copy:
            src: "{{  pv_ua_user_share_dir  }}/themes/Nordic/kde/colorschemes/"
            dest: "{{  pv_ua_user_share_dir  }}/color-schemes/"
            remote_src: true

        - name: USERAPPS | Theme | EliverLara Nordic | Copy Resources | look-and-feel
          ansible.builtin.copy:
            src: "{{  pv_ua_user_share_dir  }}/themes/Nordic/kde/plasma/look-and-feel/"
            dest: "{{  pv_ua_user_share_dir  }}/plasma/look-and-feel/"
            remote_src: true

        - name: USERAPPS | Theme | EliverLara Nordic | Copy Resources | Kvantum
          ansible.builtin.copy:
            src: "{{  pv_ua_user_share_dir  }}/themes/Nordic/kde/kvantum/"
            dest: "{{  pv_ua_user_config_dir  }}/Kvantum/"
            remote_src: true

        - name: USERAPPS | Theme | EliverLara Nordic | Copy Resources | konsole Themes
          ansible.builtin.copy:
            src: "{{  pv_ua_user_share_dir  }}/themes/Nordic/kde/konsole/"
            dest: "{{  pv_ua_user_share_dir  }}/konsole/"
            remote_src: true

        - name: USERAPPS | Theme | EliverLara Nordic | Copy Resources | Nordic-cursors
          ansible.builtin.copy:
            src: "{{  pv_ua_user_share_dir  }}/themes/Nordic/kde/cursors/Nordic-cursors/"
            dest: "{{  pv_ua_user_share_dir  }}/icons/Nordic-cursors/"
            remote_src: true

- name: USERAPPS | Theme | EliverLara Nordic-kde
  block:
    - name: USERAPPS | Theme | EliverLara Nordic-USERAPPS | Git clone
      ansible.builtin.git:
        single_branch: true
        repo: "https://github.com/EliverLara/Nordic-kde.git"
        dest: "{{  pv_ua_user_tmp_dir  }}/EliverLara-Nordic-kde-git"
        depth: 1
      register: pv_kde_tmp_eliverLara_nordic_kde_updated

    - name: USERAPPS | Theme | EliverLara Nordic-USERAPPS | Copy Resources
      when: pv_kde_tmp_eliverLara_nordic_kde_updated.changed
      block:
        - name: USERAPPS | Theme | EliverLara Nordic-USERAPPS | Copy Resources | plasma desktoptheme
          ansible.builtin.copy:
            src: "{{  pv_ua_user_tmp_dir  }}/EliverLara-Nordic-kde-git/"
            dest: "{{  pv_ua_user_share_dir  }}/plasma/desktoptheme/Nordic/"
            remote_src: true

        - name: USERAPPS | Theme | EliverLara Nordic-USERAPPS | Copy Resources | Delete git tracker
          ansible.builtin.file:
            path: "{{  pv_ua_user_share_dir  }}/plasma/desktoptheme/Nordic/.git"
            state: absent

- name: USERAPPS | Theme | vinceliuice Layan-kde
  block:
    - name: USERAPPS | Theme | vinceliuice Layan-USERAPPS | Git Clone
      ansible.builtin.git:
        single_branch: true
        repo: "https://github.com/vinceliuice/Layan-kde.git"
        dest: "{{  pv_ua_user_tmp_dir  }}/vinceliuice-Layan-kde"
        depth: 1
      register: pv_kde_tmp_layan_kde_theme_updated

    - name: USERAPPS | Theme | vinceliuice Layan-USERAPPS | Install
      ansible.builtin.shell: "{{  pv_ua_user_tmp_dir  }}/vinceliuice-Layan-kde/install.sh"
      when: pv_kde_tmp_layan_kde_theme_updated.changed
      args:
        executable: /bin/bash

- name: USERAPPS | Cursors | vinceliuice Layan-cursors
  block:
    - name: USERAPPS | Cursors | vinceliuice Layan-cursors | Git Clone
      ansible.builtin.git:
        single_branch: true
        repo: "https://github.com/vinceliuice/Layan-cursors.git"
        dest: "{{  pv_ua_user_tmp_dir  }}/vinceliuice-Layan-cursors"
        depth: 1
      register: pv_kde_tmp_layan_cursors_updated

    - name: USERAPPS | Cursors | vinceliuice Layan-cursors | Install
      ansible.builtin.shell: "{{  pv_ua_user_tmp_dir  }}/vinceliuice-Layan-cursors/install.sh"
      when: pv_kde_tmp_layan_cursors_updated.changed
      args:
        executable: /bin/bash
        chdir: "{{  pv_ua_user_tmp_dir  }}/vinceliuice-Layan-cursors"

- name: USERAPPS | Theme | vinceliuice Layan-gtk-theme
  block:
    - name: USERAPPS | Theme | vinceliuice Layan-gtk-theme | Git Clone
      ansible.builtin.git:
        single_branch: true
        repo: "https://github.com/vinceliuice/Layan-gtk-theme.git"
        dest: "{{  pv_ua_user_tmp_dir  }}/vinceliuice-Layan-gtk-theme"
        depth: 1
      register: pv_kde_tmp_layan_gtk_theme_updated

    - name: USERAPPS | Theme | vinceliuice Layan-gtk-theme | Install
      ansible.builtin.shell: "{{  pv_ua_user_tmp_dir  }}/vinceliuice-Layan-gtk-theme/install.sh"
      when: pv_kde_tmp_layan_gtk_theme_updated.changed
      args:
        executable: /bin/bash

# - name: USERAPPS | Download | Theme | EliverLara Sweet-kde
#   ansible.builtin.git:
#     single_branch: true
#     repo: 'https://github.com/EliverLara/Sweet-kde.git'
#     dest: "{{  pv_ua_user_share_dir  }}/plasma/desktoptheme/Sweet"
#     depth: 1
#     separate_git_dir: "{{  pv_ua_user_tmp_dir  }}/EliverLara-Sweet-kde-git-bare"

# - name: USERAPPS | Download | Theme | EliverLara Sweet
#   ansible.builtin.git:
#     single_branch: true
#     repo: 'https://github.com/EliverLara/Sweet.git'
#     dest: "{{  pv_ua_user_share_dir  }}/themes/Sweet"
#     depth: 1
#     separate_git_dir: "{{  pv_ua_user_tmp_dir  }}/EliverLara-Sweet-git-bare"

- name: USERAPPS | Theme | EliverLara Sweet Mars
  block:
    - name: USERAPPS | Theme | EliverLara Sweet Mars | Git Clone
      ansible.builtin.git:
        single_branch: true
        repo: "https://github.com/EliverLara/Sweet.git"
        dest: "{{  pv_ua_user_tmp_dir  }}/EliverLara-Sweet-mars-git"
        depth: 1
        version: mars
      register: pv_kde_tmp_eliverLara_Sweet_mars_updated

    - name: USERAPPS | Theme | EliverLara Sweet Mars | Copy Resources
      when: pv_kde_tmp_eliverLara_Sweet_mars_updated.changed
      block:
        - name: USERAPPS | Theme | EliverLara Sweet Mars | Copy Resources | gtk themes
          ansible.builtin.copy:
            src: "{{  pv_ua_user_tmp_dir  }}/EliverLara-Sweet-mars-git/"
            dest: "{{  pv_ua_user_share_dir  }}/themes/Sweet-mars/"
            remote_src: true

        - name: USERAPPS | Theme | EliverLara Sweet Mars | Copy Resources | Delete git tracker from gtk directory
          ansible.builtin.file:
            path: "{{  pv_ua_user_share_dir  }}/themes/Sweet-mars/.git"
            state: absent

        - name: USERAPPS | Theme | EliverLara Sweet Mars | Copy Resources | Copy aurorae themes
          ansible.builtin.copy:
            src: "{{  pv_ua_user_share_dir  }}/themes/Sweet-mars/kde/aurorae/"
            dest: "{{  pv_ua_user_share_dir  }}/aurorae/themes/"
            remote_src: true

        - name: USERAPPS | Theme | EliverLara Sweet Mars | Copy Resources | Copy color schemes
          ansible.builtin.copy:
            src: "{{  pv_ua_user_share_dir  }}/themes/Sweet-mars/kde/colorschemes/"
            dest: "{{  pv_ua_user_share_dir  }}/color-schemes/"
            remote_src: true

        - name: USERAPPS | Theme | EliverLara Sweet Mars | Copy Resources | Copy plasma schemes
          ansible.builtin.copy:
            src: "{{  pv_ua_user_share_dir  }}/themes/Sweet-mars/kde/plasma/"
            dest: "{{  pv_ua_user_share_dir  }}/plasma/"
            remote_src: true

        - name: USERAPPS | Theme | EliverLara Sweet Mars | Copy Resources | Copy Kvantum schemes
          ansible.builtin.copy:
            src: "{{  pv_ua_user_share_dir  }}/themes/Sweet-mars/kde/kvantum/"
            dest: "{{  pv_ua_user_config_dir  }}/Kvantum/"
            remote_src: true

        - name: USERAPPS | Theme | EliverLara Sweet Mars | Copy Resources | Copy konsole schemes
          ansible.builtin.copy:
            src: "{{  pv_ua_user_share_dir  }}/themes/Sweet-mars/kde/konsole/"
            dest: "{{  pv_ua_user_share_dir  }}/konsole/"
            remote_src: true

- name: USERAPPS | Copy Konsave Profiles
  ansible.builtin.copy:
    src: "files/konsave_profiles/"
    dest: "{{  pv_ua_user_config_dir  }}/konsave/profiles"
