- name: USERAPPS | Fonts | Cascadia Code | Get latest releases
  ansible.builtin.uri:
    url: "https://api.github.com/repos/microsoft/cascadia-code/releases/latest"
    method: GET
    return_content: yes
    headers:
      Accept: "application/vnd.github.v3+json"
    status_code: 200
  register: pv_ua_fonts_cascadia_latest_release

- name: USERAPPS | Fonts | Cascadia Code | Set download path
  set_fact:
    pv_ua_fonts_cascadia_download_path: "{{  pv_ua_user_tmp_dir  }}/CascadiaCode-{{  pv_ua_fonts_cascadia_latest_release.json.tag_name[1:]  }}.zip"

- name: USERAPPS | Fonts | Cascadia Code | Set download URL
  set_fact:
    pv_ua_fonts_cascadia_download_url: "https://github.com/microsoft/cascadia-code/releases/download/{{  pv_ua_fonts_cascadia_latest_release.json.tag_name  }}/CascadiaCode-{{  pv_ua_fonts_cascadia_latest_release.json.tag_name[1:]  }}.zip"

- name: USERAPPS | Fonts | Cascadia Code | Get downloaded file stat
  stat:
    path: "{{  pv_ua_fonts_cascadia_download_path  }}"
  register: pv_ua_fonts_cascadia_tmp_downloaded_file_stat

- name: USERAPPS | Fonts | Cascadia Code | Install
  when: not pv_ua_fonts_cascadia_tmp_downloaded_file_stat.stat.exists
  block:
    - name: USERAPPS | Fonts | Cascadia Code | Install | Download bin
      ansible.builtin.get_url:
        url: "{{  pv_ua_fonts_cascadia_download_url  }}"
        dest: "{{  pv_ua_fonts_cascadia_download_path  }}"

    - name: USERAPPS | Fonts | Hack | Cascadia Code | Create Directory
      ansible.builtin.file:
        path: "{{  pv_ua_user_share_dir  }}/fonts/cascadia-code"
        state: directory

    - name: USERAPPS | Fonts | Cascadia Code | Install | Copy to Fonts Directory
      ansible.builtin.unarchive:
        src: "{{  pv_ua_fonts_cascadia_download_path  }}"
        dest: "{{  pv_ua_user_share_dir  }}/fonts/cascadia-code"
        remote_src: yes

    - name: USERAPPS | Fonts | Cascadia Code | Install | Check font config
      shell: "hash fc-cache &>/dev/null"
      args:
        executable: /bin/bash
      register: pv_ua_fonts_cac_if_fontconfig_present
      changed_when: false
      ignore_errors: true

    - name: USERAPPS | Fonts | Cascadia Code | Install | Update font cache
      shell: "fc-cache -f -v {{  pv_ua_user_share_dir  }}/fonts/cascadia-code"
      args:
        executable: /bin/bash
      register: pv_ua_fonts_cascadia_update_cache_result
      when: pv_ua_fonts_cac_if_fontconfig_present.rc == 0

    - name: USERAPPS | Fonts | Cascadia Code | Install | Update Result
      debug:
        var: pv_ua_fonts_cascadia_update_cache_result
