- name: USERAPPS | JetBrains | IntelliJ IDEA Ultimate | Get Latest Version
  when: pv_jb_idea_version_ideaiu is undefined
  import_tasks: get-version.yml

- name: USERAPPS | JetBrains | IntelliJ IDEA Ultimate | Set User Defined Version
  when: pv_jb_idea_version_ideaiu is defined and pv_jb_idea_version_ideaiu | length > 1
  set_fact:
    pv_jb_idea_version: "{{  pv_jb_idea_version_ideaiu  }}"

- name: USERAPPS | JetBrains | IntelliJ IDEA Ultimate | Set Install Path
  when: pv_jb_idea_install_path_ideaiu is undefined
  set_fact:
    pv_jb_idea_install_path: "{{  pv_ua_user_share_dir  }}/JetBrains/{{  pv_jb_idea_ideaiu_or_ideaic  }}-{{  pv_jb_idea_version  }}"

- name: USERAPPS | JetBrains | IntelliJ IDEA Ultimate | Set User Install Path
  when: pv_jb_idea_install_path_ideaiu is defined and pv_jb_idea_install_path_ideaiu | length > 1
  set_fact:
    pv_jb_idea_install_path: "{{  pv_jb_idea_install_path_ideaiu  }}"

- name: USERAPPS | JetBrains | IntelliJ IDEA Ultimate | Set Url
  set_fact:
    pv_jb_idea_download_url: "https://download-cdn.jetbrains.com/idea/ideaIU-{{  pv_jb_idea_version  }}.tar.gz"

- name: USERAPPS | JetBrains | IntelliJ IDEA Ultimate | Set desktop icon Path
  when: pv_jb_idea_desktop_icon_path_ideaiu is undefined
  set_fact:
    pv_jb_idea_desktop_icon_path: "{{ pv_ua_user_share_dir }}/applications/{{  pv_jb_idea_ideaiu_or_ideaic  }}-{{ pv_jb_idea_version }}-userapps.desktop"

- name: USERAPPS | JetBrains | IntelliJ IDEA Ultimate | Set User Install Path
  when: pv_jb_idea_desktop_icon_path_ideaiu is defined and pv_jb_idea_desktop_icon_path_ideaiu | length > 1
  set_fact:
    pv_jb_idea_desktop_icon_path: "{{  pv_jb_idea_desktop_icon_path_ideaiu  }}"

- name: USERAPPS | JetBrains | IntelliJ IDEA Ultimate | Set Name
  set_fact:
    pv_jb_idea_product_name: "IntelliJ IDEA Ultimate"
